### ISSUE TITLE
Написать ТЗ

### ISSUE THREAD

**Issue by Juvelirov** [Juvelirov/hrHelper#4]
Написать ТЗ к веб-сервису, исходя из согласованного с куратором функционала. 

ТЗ должен быть очень подробным, вплоть до описания работы каждой страницы и взаимодействия кнопок между ними.

Найти примеры составления грамотного ТЗ и сделать аналогично.

Результат выполнения задачи: документ с проведенным анализом. (Прикреплять сюда)

До 11.10 23:59

**Comment by SolevarLive** [comment]
https://docs.google.com/document/d/1wDohRuw0pPswoRaQYwdXhPNmB4WUQU_W8XEkwxsdA7g/edit?tab=t.0
